name: dart_datasource_generator

description: Dart package used to automatically generate datasources, repository and models. 

version: 0.0.2

repository: https://github.com/krikristoophe/dart_datasource_generator/tree/master/dart_datasource_generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: '>=5.0.0 <7.0.0'
  build: ^2.4.1
  dart_datasource_models: ^0.0.3
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  meta: '>=1.9.0 <2.0.0'
  mockito: ^5.4.2
  recase: ^4.1.0
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.21.0
  very_good_analysis: ^5.1.0

dependency_overrides:
  dart_datasource_models:
    path: ../dart_datasource_models/
